### PR TITLE
Fix for building with some repo trees

### PR DESCRIPTION
**Pull request by BitOBSessiOn**
Needed for some newer mr_hooks.c implementations

### CODE REVIEW

**Comment by BitOBSessiOn** [comment]
More work pending on other files... Closed.

**Comment by BitOBSessiOn** [comment]
Commit amended.

**Comment by nkk71** [comment]
Why would you want to merge into an obsolete -tmp branch?
Maybe I'm missing the point, but build for omni-6.0 tree was fixed a while back in the normal branch, and I have hesitations using -Wno-error=implicit-function-declaration in any branch.
As for 7.1 tree, I have not yet decided how I personally wish to proceed with this. I know there are "fixups" elsewhere, not entirely certain if that is how to proceed or not.

**Comment by BitOBSessiOn** [comment]
Sorry, my fault... I was playing with multirom repo and switched to wrong branch.
I also doubt about using -Wno-error... it can be a quick fix but sometimes it can cloak other issues.
I close this and focus only on main branch. Thx.

**Pull request closed without merging**
